twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        image_cuvee_location: '%image_cuvee_location%'
        image_news_location: '%image_news_location%'
        photo_location: '%photo_location%'
