version: '3.5'
services:
    vienais-web:
        container_name: vienais-web
        image: vienais-web
        environment:
            SYMFONY_ENV: dev
        volumes:
            - .:/app
        ports:
            - 8037:80

    vienais-db:
        container_name: vienais-db
        image: mysql:5.7
        ports:
            - 6603:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "vienais"

    vienais-phpmyadmin:
        container_name: vienais-phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            TESTSUITE_PASSWORD: "password"
            PMA_HOST: vienais-db
        depends_on:
            - vienais-db
        ports:
            - 8038:80

